language: groovy
services:
  - redis
  - mongodb
jdk:
- oraclejdk7
env:
   - TERM=dumb GRADLE_OPTS="-Xmx2048m -Xms256m -XX:MaxPermSize=768m -XX:+CMSClassUnloadingEnabled -XX:+HeapDumpOnOutOfMemoryError" 
script: ./travis-build.sh