language: groovy
services:
  - redis
  - mongodb
before_install:
  - "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"  
jdk:
- oraclejdk7
env:
   - TERM=dumb
script: ./travis-build.sh